site_name: 'CITZ IMB Express Utilities (NPM Package)'
site_description: 'An npm package that provides utility functions for Express APIs, aimed at reducing code complexity, enhancing data integrity and security, and promoting consistency and scalability.'
docs_dir: 'techdocs/docs'
repo_url: 'https://github.com/bcgov/citz-imb-express-utilities'
edit_uri: edit/main/techdocs/docs
nav:
  - Introduction: index.md
  - Getting Started:
      - Installing the Package: getting-started/installing-the-package.md
      - Quick Start Guide: getting-started/quick-start-guide.md
  - Using The Package:
      - APIs & Components:
          - Middleware: using-the-package/apis-&-components/middleware.md
          - Modules:
              - healthModule: using-the-package/apis-&-components/modules/health.md
              - configModule: using-the-package/apis-&-components/modules/config.md
          - errorWrapper: using-the-package/apis-&-components/error-wrapper.md
          - standardResponse: using-the-package/apis-&-components/standard-response.md
          - serverStartupLogs: using-the-package/apis-&-components/server-startup-logs.md
          - sanitize: using-the-package/apis-&-components/sanitize.md
          - Ansi Codes: using-the-package/apis-&-components/ansi-codes.md
          - HttpError: using-the-package/apis-&-components/http-error.md
          - HTTP_STATUS_CODES: using-the-package/apis-&-components/http-status-codes.md
          - Zod:
              - Param Validation:
                  - Req Params: using-the-package/apis-&-components/zod/request-schema-validation/get-zod-validated-params.md
                  - Req Query: using-the-package/apis-&-components/zod/request-schema-validation/get-zod-validated-query.md
                  - Req Body: using-the-package/apis-&-components/zod/request-schema-validation/get-zod-validated-body.md
                  - stringParam: using-the-package/apis-&-components/zod/route-params/string-param.md
                  - booleanParam: using-the-package/apis-&-components/zod/route-params/boolean-param.md
                  - numberParam: using-the-package/apis-&-components/zod/route-params/number-param.md
                  - integerParam: using-the-package/apis-&-components/zod/route-params/integer-param.md
              - .refine:
                  - refineAtLeastOneNonEmpty: using-the-package/apis-&-components/zod/refine-functions/at-least-one-non-empty.md
              - .transform:
                  - transformRemoveEmpty: using-the-package/apis-&-components/zod/transform-functions/remove-empty.md
      - Module Exports: using-the-package/module-exports.md
      - TypeScript Types: using-the-package/typescript-types.md
  - Major Releases:
      - 1.0.0: major-releases/major-release-1.md

plugins:
  - techdocs-core
  - git-revision-date-localized
markdown_extensions:
  - md_in_html
