site_name: 'CITZ IMB Express Utilities (NPM Package)'
site_description: 'An npm package that provides utility functions for Express APIs, aimed at reducing code complexity, enhancing data integrity and security, and promoting consistency and scalability.'
docs_dir: 'techdocs/docs'
repo_url: 'https://github.com/bcgov/citz-imb-express-utilities'
edit_uri: edit/main/techdocs/docs
nav:
  - Introduction: index.md
  - Getting Started:
      - Installing the Package: getting-started/installing-the-package.md
  - Using The Package:
      - APIs & Components:
          - errorWrapper: using-the-package/apis-&-components/error-wrapper.md
          - Zod:
              - Middleware: using-the-package/apis-&-components/zod/zod-validation-middleware.md
              - Param Validation:
                  - getZodValidatedParams: using-the-package/apis-&-components/zod/request-schema-validation/get-zod-validated-params.md
                  - getZodValidatedQuery: using-the-package/apis-&-components/zod/request-schema-validation/get-zod-validated-query.md
                  - getZodValidatedBody: using-the-package/apis-&-components/zod/request-schema-validation/get-zod-validated-body.md
                  - stringParam: using-the-package/apis-&-components/zod/route-params/string-param.md
                  - booleanParam: using-the-package/apis-&-components/zod/route-params/boolean-param.md
                  - numberParam: using-the-package/apis-&-components/zod/route-params/number-param.md
                  - integerParam: using-the-package/apis-&-components/zod/route-params/integer-param.md
              - .refine:
                  - refineAtLeastOneNonEmpty: using-the-package/apis-&-components/zod/refine-functions/at-least-one-non-empty.md
              - .transform:
                  - transformRemoveEmpty: using-the-package/apis-&-components/zod/transform-functions/remove-empty.md
      - Module Exports: using-the-package/module-exports.md
      - TypeScript Types: using-the-package/typescript-types.md
  - Major Releases:
      - 1.0.0: major-releases/major-release-1.md

plugins:
  - techdocs-core
  - git-revision-date-localized
markdown_extensions:
  - md_in_html
